-- MySQL Script generated by MySQL Workbench
-- Wed May 12 19:31:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usuariodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuariodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuariodb` DEFAULT CHARACTER SET utf8mb4 ;
USE `usuariodb` ;

-- -----------------------------------------------------
-- Table `usuariodb`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`LOCALIDAD` (
  `idLocalidad` INT NOT NULL,
  `DescrpcionLocalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`AFILIADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`AFILIADO` (
  `idAfiliado` INT NOT NULL,
  `NombreAfiliado` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  `LOCALIDAD_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idAfiliado`),
  INDEX `fk_AFILIADO_LOCALIDAD_idx` (`LOCALIDAD_idLocalidad` ASC) ,
  CONSTRAINT `fk_AFILIADO_LOCALIDAD`
    FOREIGN KEY (`LOCALIDAD_idLocalidad`)
    REFERENCES `usuariodb`.`LOCALIDAD` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`TIPO_PRESENTACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`TIPO_PRESENTACION` (
  `idTipoPresentacion` INT NOT NULL,
  `DrescripcionTipoPresentacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoPresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`MEDICAMENTO` (
  `idMedicamento` INT NOT NULL,
  `NombreMedicamento` VARCHAR(45) NULL,
  `FechaAlta` DATE NULL,
  `TIPO_PRESENTACION_idTipoPresentacion` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  INDEX `fk_MEDICAMENTO_TIPO_PRESENTACION1_idx` (`TIPO_PRESENTACION_idTipoPresentacion` ASC) ,
  CONSTRAINT `fk_MEDICAMENTO_TIPO_PRESENTACION1`
    FOREIGN KEY (`TIPO_PRESENTACION_idTipoPresentacion`)
    REFERENCES `usuariodb`.`TIPO_PRESENTACION` (`idTipoPresentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`MONODROGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`MONODROGA` (
  `idMonodroga` INT NOT NULL,
  `NombreMonodroga` VARCHAR(45) NULL,
  PRIMARY KEY (`idMonodroga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`FARMACIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`FARMACIA` (
  `idFarmacia` INT NOT NULL,
  `NombreFarmacia` VARCHAR(45) NULL,
  `FechaApertura` DATE NULL,
  `LOCALIDAD_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idFarmacia`),
  INDEX `fk_FARMACIA_LOCALIDAD1_idx` (`LOCALIDAD_idLocalidad` ASC) ,
  CONSTRAINT `fk_FARMACIA_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_idLocalidad`)
    REFERENCES `usuariodb`.`LOCALIDAD` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`COMPOSICION-MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`COMPOSICION-MEDICAMENTO` (
  `MONODROGA_idMonodroga` INT NOT NULL,
  `MEDICAMENTO_idMedicamento` INT NOT NULL,
  `CantidadMonodroga` DECIMAL(5) NULL,
  `MONODROGA_has_MEDICAMENTOcol` VARCHAR(45) NULL,
  PRIMARY KEY (`MONODROGA_idMonodroga`, `MEDICAMENTO_idMedicamento`),
  INDEX `fk_MONODROGA_has_MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_idMedicamento` ASC) ,
  INDEX `fk_MONODROGA_has_MEDICAMENTO_MONODROGA1_idx` (`MONODROGA_idMonodroga` ASC) ,
  CONSTRAINT `fk_MONODROGA_has_MEDICAMENTO_MONODROGA1`
    FOREIGN KEY (`MONODROGA_idMonodroga`)
    REFERENCES `usuariodb`.`MONODROGA` (`idMonodroga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MONODROGA_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_idMedicamento`)
    REFERENCES `usuariodb`.`MEDICAMENTO` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`CONSUMO-AFILIADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`CONSUMO-AFILIADO` (
  `AFILIADO_idAfiliado` INT NOT NULL,
  `MEDICAMENTO_idMedicamento` INT NOT NULL,
  `FechaHoraConsumo` DATETIME NOT NULL,
  `FARMACIA_idFarmacia` INT NOT NULL,
  `CantidadConsumida` DECIMAL(5) NULL,
  `AFILIADO_has_MEDICAMENTOcol` VARCHAR(45) NULL,
  `PrecioUnitario` INT NULL,
  `AFILIADO_has_MEDICAMENTOcol1` VARCHAR(45) NULL,
  PRIMARY KEY (`AFILIADO_idAfiliado`, `MEDICAMENTO_idMedicamento`),
  INDEX `fk_AFILIADO_has_MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_idMedicamento` ASC) ,
  INDEX `fk_AFILIADO_has_MEDICAMENTO_AFILIADO1_idx` (`AFILIADO_idAfiliado` ASC) ,
  INDEX `fk_AFILIADO_has_MEDICAMENTO_FARMACIA1_idx` (`FARMACIA_idFarmacia` ASC) ,
  CONSTRAINT `fk_AFILIADO_has_MEDICAMENTO_AFILIADO1`
    FOREIGN KEY (`AFILIADO_idAfiliado`)
    REFERENCES `usuariodb`.`AFILIADO` (`idAfiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFILIADO_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_idMedicamento`)
    REFERENCES `usuariodb`.`MEDICAMENTO` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFILIADO_has_MEDICAMENTO_FARMACIA1`
    FOREIGN KEY (`FARMACIA_idFarmacia`)
    REFERENCES `usuariodb`.`FARMACIA` (`idFarmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariodb`.`PRECIO-MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariodb`.`PRECIO-MEDICAMENTO` (
  `FechaPrecio` DATE NOT NULL,
  `Precio` INT NULL,
  `MEDICAMENTO_idMedicamento` INT NOT NULL,
  INDEX `fk_PRECIO-MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_idMedicamento` ASC) ,
  CONSTRAINT `fk_PRECIO-MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_idMedicamento`)
    REFERENCES `usuariodb`.`MEDICAMENTO` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
